import java.net.URI;
import java.util.UUID;

import software.amazon.awssdk.auth.credentials.AwsCredentials;
import software.amazon.awssdk.core.sync.RequestBody;
import software.amazon.awssdk.services.s3.S3Client;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {

    private static class TestAwsCredentials implements AwsCredentials {

        @Override
        public String accessKeyId() {
            return "minio";
        }

        @Override
        public String secretAccessKey() {
            return "minio123";
        }

    }
    public static void main(String[] args) throws Exception {
        String bucketName = UUID.randomUUID().toString();
        S3Client s3Client = S3Client.builder()
            .endpointOverride(new URI("http://localhost:9000"))
            .credentialsProvider(() -> new TestAwsCredentials())
            .build();
        s3Client.createBucket(builder -> builder.bucket(bucketName));
        try {
            s3Client.putObject(builder -> builder.bucket(bucketName).key("key"), RequestBody.fromString("sdf"));
        } finally {
            s3Client.deleteBucket(builder -> builder.bucket(bucketName));
        }
    }
}
